export enum ErrorCode {
  // sort
  INVALID_SORT_ORDER = 'INVALID_SORT_ORDER',

  INVALID_REQUEST_DATA = 'INVALID REQUEST DATA',
  // Authorization
  USER_NOT_AUTHORIZED = 'USER NOT AUTHORIZED',
  // Users
  USER_ALREADY_EXISTS = 'USER ALREADY EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND'
}
