export enum ErrorCode {
  // sort
  INVALID_SORT_ORDER = 'INVALID_SORT_ORDER',

  INVALID_REQUEST_DATA = 'INVALID REQUEST DATA',
  // Authorization
  USER_NOT_AUTHORIZED = 'USER NOT AUTHORIZED',
  // Users
  USER_ALREADY_EXISTS = 'USER ALREADY EXISTS',
  USERNAME_OR_PASSWORD_WRONG = 'USERNAME OR PASSWORD WRONG',
  USERNAME_OR_PASSWORD_NOT_FOUND = 'USERNAME OR PASSWORD NOT FOUND',
  INVALID_USER_PRIVILEGE = 'INVALID USER PRIVILEGE',
  // notification
  INVALID_INTEREST_TYPE = 'INVALID INTEREST TYPE'
}
